# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Font TypeKit Generation Action
      uses: sharadcodes/font-typekit-generator-action@v1.0
      with:
        input-folder: "my_fonts" # This is a Required field & this folder has original font files in TTF format
        output-folder: "converted_fonts" # This is a Required field & this folder will be used to store converted font files
    - name: Add & Commit files
      run: |
        git config --local user.email "sharadcodes@github.com"
        git config --local user.name "sharadcodes"
        git add .
        git commit -m "Add changes" -a
        git push -f -q https://${{ secrets.GITHUB_TOKEN }}@github.com/sharadcodes/myfonts.git master
